import{dateFromSearch,fetchReport,nextAvailableDate,previousAvailableDate,sortedReportDates,taipeiDay}from'./scripts/archive-utils.mjs';

const state={items:[],filter:'全部',query:'',saved:new Set(JSON.parse(localStorage.getItem('saved')||'[]')),dates:[],selectedDate:null,latestDate:null};const feed=document.querySelector('#feed');const template=document.querySelector('#card-template');const empty=document.querySelector('#empty');const status=document.querySelector('#feed-status');
function formatDate(value){return new Intl.DateTimeFormat('zh-TW',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Taipei'}).format(new Date(value));}
function formatReportDate(date){return new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date(`${date}T12:00:00+08:00`));}
function setLoading(loading){status.hidden=!loading;status.textContent=loading?'正在載入報告…':'';document.querySelector('#previous-day').disabled=loading||!previousAvailableDate(state.dates,state.selectedDate||state.latestDate||'');document.querySelector('#next-day').disabled=loading||!state.selectedDate||!nextAvailableDate(state.dates,state.selectedDate);}
function render(){const query=state.query.toLowerCase();const items=state.items.filter(item=>(state.filter==='全部'||item.category===state.filter)&&`${item.title} ${item.summary} ${item.opportunity}`.toLowerCase().includes(query));feed.replaceChildren(...items.map(item=>{const node=template.content.firstElementChild.cloneNode(true);node.dataset.id=item.id;node.querySelector('.category').textContent=item.category;const link=node.querySelector('.title');link.textContent=item.title;link.href=item.url;node.querySelector('.summary').textContent=item.summary;node.querySelector('.relevance').textContent=item.whyItMatters;node.querySelector('.opportunity').textContent=item.opportunity;node.querySelector('.action').textContent=item.action;node.querySelector('.source').textContent=item.source;node.querySelector('time').textContent=formatDate(item.publishedAt);node.querySelector('.score').textContent=`分數 ${item.score}`;const save=node.querySelector('.save');save.textContent=state.saved.has(item.id)?'★':'☆';save.setAttribute('aria-label',state.saved.has(item.id)?'取消收藏':'收藏');save.classList.toggle('saved',state.saved.has(item.id));save.addEventListener('click',()=>{state.saved.has(item.id)?state.saved.delete(item.id):state.saved.add(item.id);localStorage.setItem('saved',JSON.stringify([...state.saved]));render();});return node;}));empty.hidden=items.length>0;if(!items.length)empty.textContent=state.query||state.filter!=='全部'?'沒有符合篩選條件的機會。':'這一天尚無可顯示的機會。';}
function renderFilters(){const categories=['全部',...new Set(state.items.map(item=>item.category))];document.querySelector('#filters').replaceChildren(...categories.map(category=>{const button=document.createElement('button');button.textContent=category;button.classList.toggle('active',category===state.filter);button.onclick=()=>{state.filter=category;renderFilters();render();};return button;}));}
function updateNavigation(){const date=state.selectedDate||state.latestDate||taipeiDay();document.querySelector('#selected-date').textContent=state.selectedDate?formatReportDate(date):`最新報告（${formatReportDate(date)}）`;document.querySelector('#date-picker').value=date;document.querySelector('#date-picker').max=state.latestDate||'';document.querySelector('#latest').hidden=!state.selectedDate;setLoading(false);}
async function loadIndex(){try{const response=await fetch('data/archive/index.json',{cache:'no-store'});if(!response.ok)throw new Error();const index=await response.json();state.dates=sortedReportDates(index.dates||[]);}catch{state.dates=[];}}
async function loadCurrent(){const selected=dateFromSearch(location.search);state.selectedDate=selected;setLoading(true);try{const data=await fetchReport(fetch,selected);state.items=Array.isArray(data.items)?data.items:[];state.latestDate=taipeiDay(new Date(data.generatedAt));if(!state.dates.includes(state.latestDate))state.dates=sortedReportDates([...state.dates,state.latestDate]);document.querySelector('#updated').textContent=`更新於 ${formatDate(data.generatedAt)}`;document.querySelector('#count').textContent=`${state.items.length} 個機會`;state.filter='全部';renderFilters();render();}catch{state.items=[];document.querySelector('#updated').textContent=selected?'找不到此日期的報告':'無法載入最新報告';document.querySelector('#count').textContent='';state.filter='全部';renderFilters();render();empty.hidden=false;empty.textContent=selected?`${formatReportDate(selected)} 尚無報告。請選擇其他日期或查看最新報告。`:'目前無法載入報告，請稍後再試。';}updateNavigation();}
function goTo(date){const url=new URL(location.href);if(date)url.searchParams.set('date',date);else url.searchParams.delete('date');history.pushState({},'',url);loadCurrent();}
document.querySelector('#search').addEventListener('input',event=>{state.query=event.target.value;render();});document.querySelector('#theme').addEventListener('click',()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('theme',document.documentElement.classList.contains('dark')?'dark':'light');});document.querySelector('#previous-day').addEventListener('click',()=>goTo(previousAvailableDate(state.dates,state.selectedDate||state.latestDate)));document.querySelector('#next-day').addEventListener('click',()=>goTo(nextAvailableDate(state.dates,state.selectedDate)));document.querySelector('#date-picker').addEventListener('change',event=>goTo(event.target.value));document.querySelector('#latest').addEventListener('click',()=>goTo(null));window.addEventListener('popstate',loadCurrent);if(localStorage.getItem('theme')==='dark')document.documentElement.classList.add('dark');await loadIndex();loadCurrent();
